top_k: 10

constraints:
  chemistry_status: complete

  inputs:
    OPC:
      max: 55.0
    w_b:
      min: 0.30
      max: 0.40

  validated_targets:
    porosity:
      max: 0.292
    C-A-S-H:
      min: 0.050
    Calcite:
      max: 0.001
    Portlandite:
      max: 0.0001

  prediction_errors:
    porosity:
      max_abs: 0.01
    C-A-S-H:
      max_abs: 0.0025

objectives:
  minimize:
    validated_targets:
      porosity: 0.8
      Calcite: 1.0
      Portlandite: 0.5
    inputs:
      OPC: 0.3

  maximize:
    validated_targets:
      C-A-S-H: 1.0
      ettringite: 0.2

score:
  normalize: minmax
